### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by ayunami2000** [zuranthus/LivePaper#9]
The application seems to silently exit on windows 7. Specifically, Aero is disabled and I am not able to test it with Aero enabled. I know [weebp](https://github.com/Francesco149/weebp) solves this with the side effect of covering the desktop icons, so I wonder if this program can do the same?

**Comment by ayunami2000** [comment]
I have just tried it on a windows 11 computer and it also did not seem to do anything. It does work on windows 10 though. I used RDP to access it though so idk if thats part of the issue.

**Comment by zuranthus** [comment]
Thanks for testing! It should work on Windows 7 now (both with and without Aero). Though icons will be covered if Aero is disabled, same as weebp.

> I have just tried it on a windows 11 computer and it also did not seem to do anything. It does work on windows 10 though. I used RDP to access the windows 11 computer though so idk if thats part of the issue.

I develop on Win 11 and the app works fine, so it is probably because of RDP...
